### PR TITLE
Use user identify from $LIMA_HOME/_config/user

### LINKED ISSUE #78: Make ssh keys configurable
Right now lima adds all `~/.ssh/*.pub` keys as authorized keys to the guest OS and lets ssh pick a key to authenticate.

lima will not work unless the user has at least one key pair, and asks them to run `ssh-keygen` when there isn't one.

For embedding lima in Rancher Desktop, we would want to create a key pair independently of what the user does, and not store it under `~/ssh` because that should only be done by the user themselves.

I'm proposing to authorize a key from `$LIMA_HOME/_config/user.pub` and use `$LIMA_HOME/_config/user.key` as the identity file, if those files exist, and fall back on the current behaviour if they don't.

I've choosen `$LIMA_HOME/_config` because there seemed to be tentative agreement already in #63 on using `$LIMA_HOME/_cache` for the cache.

I'm happy to implement this, but wanted to make sure first that this approach is agreeable.

### PR DESCRIPTION
**Pull request by jandubois**
By default lima uses the public keys from `~/.ssh/*.pub`.

This change makes it try `$LIME_HOME/_config/user.pub` first and only fall back on the `~/.ssh/*.pub` keys when that one does not exist. It will create the key under `$LIMA_HOME/_config` if there aren't any public keys under `~/.ssh`.

Fixes #78

### CODE REVIEW

File: pkg/sshutil/sshutil.go [hunk 1]
```diff
@@ -18,34 +19,74 @@ type PubKey struct {
...
 
-// DefaultPubKeys finds ssh public keys from ~/.ssh
+func readPublicKey(f string) (PubKey, error) {
+	entry := PubKey{
+		Filename: f,
+	}
+	content, err := os.ReadFile(f)
+	if err == nil {
+		entry.Content = strings.TrimSpace(string(content))
+	} else {
```
Comment (AkihiroSuda) [inline pkg/sshutil/sshutil.go:29]: Return err if !error.Is(err, os.ErrNorExist)

File: pkg/sshutil/sshutil.go [hunk 2]
```diff
@@ -18,34 +19,74 @@ type PubKey struct {
...
-	homeDir, err := os.UserHomeDir()
+	// Read $LIMA_HOME/_config/user.pub
+	configDir, err := store.LimaConfigDir()
+	privateKeyPath := filepath.Join(configDir, "user")
 	if err != nil {
 		logrus.Warn(err)
-		return nil
+	} else {
+		// Check that private key exists and then try to read public key
+		if _, err := os.Stat(privateKeyPath); err == nil {
```
Comment (AkihiroSuda) [inline pkg/sshutil/sshutil.go:47]: Return err if !error.Is(err, os.ErrNorExist)

File: pkg/sshutil/sshutil.go [hunk 3]
```diff
@@ -83,5 +124,12 @@ func SSHArgs(instDir string) ([]string, error) {
 		"-o", "Compression=no",
 		"-o", "BatchMode=yes",
 	}
+	configDir, err := store.LimaConfigDir()
+	if err == nil {
```
Comment (AkihiroSuda) [inline pkg/sshutil/sshutil.go:128]: Return err if !error.Is(err, os.ErrNorExist)

File: pkg/sshutil/sshutil.go [hunk 4]
```diff
@@ -83,5 +124,12 @@ func SSHArgs(instDir string) ([]string, error) {
...
+		privateKeyPath := filepath.Join(configDir, "user")
+		if _, err := os.Stat(privateKeyPath); err == nil {
```
Comment (AkihiroSuda) [inline pkg/sshutil/sshutil.go:130]: Return err if !error.Is(err, os.ErrNorExist)

File: pkg/sshutil/sshutil.go [hunk 5]
```diff
@@ -18,34 +19,74 @@ type PubKey struct {
...
+			}
 		}
-		res = append(res, entry)
 	}
-	return res
+	// Create $LIMA_HOME/_config/user (and $LIMA_HOME/_config/user.pub)
+	if configDir == "" {
+		return nil
+	}
+	keygenCmd := exec.Command("ssh-keygen", "-q", "-N", "", "-f", privateKeyPath)
```
Comment (AkihiroSuda) [inline pkg/sshutil/sshutil.go:81]: Can we specify algo explicitly?

File: pkg/sshutil/sshutil.go [hunk 6]
```diff
@@ -18,34 +19,74 @@ type PubKey struct {
...
+	if out, err := keygenCmd.CombinedOutput(); err != nil {
```
Comment (AkihiroSuda) [inline pkg/sshutil/sshutil.go:82]: logrus.Debugf(“executing %v”, keygenCmd.Args)

File: pkg/sshutil/sshutil.go (hunk 5 above)
Comment (AkihiroSuda) [reply pkg/sshutil/sshutil.go:81]: Perhaps ed25519 is fine

File: pkg/store/store.go [hunk 7]
```diff
@@ -29,6 +29,20 @@ func LimaDir() (string, error) {
 	return dir, nil
 }
 
+// LimaConfigDir returns the path of the config directory, $LIMA_HOME/_config.
+// It will create the directory if it doesn't yet exist.
```
Comment (AkihiroSuda) [inline pkg/store/store.go:33]: I’m not sure this function should make the dir.

File: pkg/store/store.go [hunk 8]
```diff
@@ -29,6 +29,20 @@ func LimaDir() (string, error) {
...
+func LimaConfigDir() (string, error) {
+	limaDir, err := LimaDir()
+	if err != nil {
+		return "", err
+	}
+	configDir := filepath.Join(limaDir, "_config")
```
Comment (AkihiroSuda) [inline pkg/store/store.go:39]: “_config” should be a constant.

File: pkg/sshutil/sshutil.go (hunk 1 above)
Comment (jandubois) [reply pkg/sshutil/sshutil.go:29]: Why? If `ReadFile` returns an error, `content` cannot be used, and we should return the error, regardless of what it is.

It will just be written to the log, and then ignored because `DefaultPubKeys` doesn't return an error. Maybe it should?

File: pkg/sshutil/sshutil.go (hunk 2 above)
Comment (jandubois) [reply pkg/sshutil/sshutil.go:47]: `DefaultPubKeys` doesn't return any errors; it just ignores key files it cannot read. So not sure what to do here.

In the end the user would be told to run `ssh-keygen` when `DefaultPubKeys` returns an empty list, so not sure that aborting on the first error is really helpful.

File: pkg/store/store.go (hunk 7 above)
Comment (jandubois) [reply pkg/store/store.go:33]: Yeah, it is inconsistent with what `LimaDir` does, but I was thinking about letting that one create the directory too. Would that simplify the calling code?

File: pkg/store/store.go (hunk 8 above)
Comment (jandubois) [reply pkg/store/store.go:39]: Yes, I was tempted to put it into `store/filenames`, but that package claims it only defines names for the instance directories. So where should `_config` be defined? New package?

Comment (AkihiroSuda) [reply pkg/store/store.go:39]: pkg/store.ConfigDir

**Comment by jandubois** [comment]
@AkihiroSuda I believe I've addresses all issues you pointed out. Can you please confirm?

But I'm wondering now if the `user` filename shouldn't be a constant too, but again don't know where to put it.

Should `store/filenames` be extended to cover both config and instance filenames?

File: pkg/sshutil/sshutil.go (hunk 1 above)
Comment (jandubois) [reply pkg/sshutil/sshutil.go:29]: This is now handled by the caller; any error is reported back to the caller because we are only calling `readPublicKey` on files that are supposed to exist.

**Comment by jandubois** [comment]
Sorry, I refactored `DefaultPubKeys` once more, so that it can actually reflect an error back to the caller.

By tightening the error handling I've also reduced the logic nesting level a bit, as it was getting out of hand.

I've also gone ahead and added other file and directory names to the `filenames` package. Let me know, if this is not how you want it to be!

I believe I'm done with it now (unless you have more feedback).

**Comment by jandubois** [comment]
@AkihiroSuda The latest CI failure is different, but I've seen a lot of errors like this before:

```
time="2021-06-28T21:49:58Z" level=fatal msg="failed to resolve reference \"ghcr.io/stargz-containers/nginx:1.19-alpine-org\": failed to do request: Head \"https://ghcr.io/v2/stargz-containers/nginx/manifests/1.19-alpine-org\": net/http: TLS handshake timeout"
```

Any idea why that is happening? You would think the connection between gha and ghcr should be pretty solid...

**Comment by AkihiroSuda** [comment]
I guess macOS instances might be running on a different infra that isn't optimal for ghcr?

File: pkg/sshutil/sshutil.go [hunk 9]
```diff
@@ -19,34 +20,71 @@ type PubKey struct {
...
+	}
+	_, err = os.Stat(filepath.Join(configDir, filenames.UserPrivateKey))
+	if err != nil {
+		if !errors.Is(err, os.ErrNotExist) {
+			return nil, err
+		}
+		if err := os.MkdirAll(configDir, 0700); err != nil {
+			return nil, errors.Wrapf(err, "could not create %q directory", configDir)
+		}
+		keygenCmd := exec.Command("ssh-keygen", "-t", "ed25519", "-q", "-N", "", "-f",
```
Comment (AkihiroSuda) [inline pkg/sshutil/sshutil.go:54]: We should lock the directory. I can open a follow-up PR.

**Review by AkihiroSuda — APPROVED** [review]

File: pkg/sshutil/sshutil.go [hunk 10]
```diff
@@ -77,7 +115,17 @@ func SSHArgs(instDir string) ([]string, error) {
...
+	if err != nil {
+		return nil, err
+	}
+	privateKeyPath := filepath.Join(configDir, filenames.UserPrivateKey)
+	_, err = os.Stat(privateKeyPath)
+	if err != nil {
+		return nil, err
+	}
 	args := []string{
+		"-i", privateKeyPath,
```
Comment (AkihiroSuda) [inline pkg/sshutil/sshutil.go:128]: Question: would it be possible to let ssh read both `~/.lima/_config` keys and `~/.ssh` keys?

Otherwise this will break existing instances.

Comment (jandubois) [reply pkg/sshutil/sshutil.go:128]: > Question: would it be possible to let ssh read both `~/.lima/_config` keys and `~/.ssh` keys?

Yes, you can specify multiple `-i` options, and the identities will be tried in sequence. I think the server may be limiting the number of attempts to 3, so it could still fail if the user added multiple keys after creating the instance. But that is already a problem with the current implementation, so doesn't change anything. Just another reason to have a lima-specific identity, and always specify that one first.

Comment (jandubois) [reply pkg/sshutil/sshutil.go]: > Question: would it be possible to let ssh read both `~/.lima/_config` keys and `~/.ssh` keys?

I've pushed the change in a separate commit for easier review; lmk if you want me to squash it!

**Review by AkihiroSuda — APPROVED** [review]
Thanks
